// All customizable labels with their default values
// Keys use dot notation: module.context.element

export const DEFAULT_LABELS: Record<string, string> = {
  // ===== Navigation =====
  'nav.main': 'Основное',
  'nav.command_center': 'Пункт управления',
  'nav.org_chart': 'Оргсхема',
  'nav.employees': 'Сотрудники',
  'nav.academy': 'Академия',
  'nav.statistics': 'Статистики',
  'nav.stats_dashboard': 'Дашборд ОС',
  'nav.departments': 'Департаменты',
  'nav.tools': 'Инструменты',
  'nav.admin_scale': 'Админ Шкала',
  'nav.config': 'Конфигурация',
  'nav.settings': 'Настройки',
  'nav.logout': 'Выход',
  'nav.employees_count': 'Сотрудников',

  // ===== Mobile nav =====
  'mobile.home': 'Главная',
  'mobile.org_chart': 'Оргсхема',
  'mobile.employees': 'Персонал',
  'mobile.academy': 'Академия',
  'mobile.statistics': 'Статистика',

  // ===== Header =====
  'header.search': 'Поиск сотрудников... ⌘K',
  'header.add_employee': 'Сотрудник',
  'header.dashboard': 'Дашборд ОС',
  'header.session': 'Текущая сессия',

  // ===== Academy =====
  'academy.title': 'Академия',
  'academy.subtitle': 'Система обучения по контрольным листам',
  'academy.courses_count': 'курсов',
  'academy.create_course': 'Создать курс',
  'academy.tab.courses': 'Курсы',
  'academy.tab.progress': 'Прогресс',
  'academy.tab.checkouts': 'Чек-ауты',
  'academy.tab.glossary': 'Глоссарий',
  'academy.tab.barriers': 'Барьеры',
  'academy.tab.docs': 'Документация',
  'academy.new_course': 'Новый курс',
  'academy.course_name': 'Название',
  'academy.course_duration': 'Длительность (часов)',
  'academy.course_description': 'Описание',
  'academy.btn_create': 'Создать',
  'academy.btn_cancel': 'Отмена',
  'academy.no_courses': 'Нет курсов. Создайте первый!',
  'academy.status_active': 'Активен',
  'academy.status_draft': 'Черновик',
  'academy.items_count': 'пунктов',
  'academy.delete_course': 'Удалить курс?',
  'academy.loading': 'Загрузка...',

  // Academy - Step types
  'step.read': 'Изучение материала',
  'step.write': 'Эссе / письменный ответ',
  'step.demo': 'Демонстрация',
  'step.clay_demo': 'Глиняная демонстрация',
  'step.drill': 'Практическое упражнение',
  'step.checkout': 'Чек-аут',
  'step.word_clearing': 'Прояснение слов',
  'step.starrate': 'Звёздочная проверка',
  'step.quiz': 'Тест / Квиз',

  // Academy - Barriers
  'barriers.title': 'Аналитика по барьерам к обучению',
  'barriers.unclear_words': 'Непонятые слова',
  'barriers.checkouts': 'Чек-ауты',
  'barriers.first_pass': '% зачёта с 1 раза',
  'barriers.stuck': 'Застряли',
  'barriers.stuck_desc': '<50% за 7+ дней',
  'barriers.cleared': 'Прояснено',
  'barriers.remaining': 'Осталось',
  'barriers.approved': 'Зачёт',
  'barriers.rejected': 'Пересдача',
  'barriers.top_words': 'Самые частые непонятые слова',
  'barriers.indicators': 'Индикаторы барьеров',
  'barriers.unclear_words_barrier': '🔤 Непонятые слова',
  'barriers.unclear_words_warn': 'непрояснённых слов — рекомендуется word clearing',
  'barriers.unclear_words_ok': '✅ Ситуация под контролем',
  'barriers.no_mass': '📦 Отсутствие массы',
  'barriers.no_mass_warn': 'Много пересдач — возможно, не хватает демонстраций',
  'barriers.no_mass_ok': '✅ Демо и практика работают',
  'barriers.steep_gradient': '📈 Крутой градиент',
  'barriers.steep_gradient_warn': 'студентов застряли — проверьте градиент сложности',
  'barriers.steep_gradient_ok': '✅ Темп обучения нормальный',

  // Academy - Word Clearing
  'wc.title': 'Непонятое слово',
  'wc.panel_title': 'Прояснение слов',
  'wc.mark_word': 'Не понимаю слово',
  'wc.cleared': 'Прояснено',
  'wc.not_cleared': 'Не прояснено',

  // Academy - Glossary
  'glossary.title': 'Глоссарий',
  'glossary.add_term': 'Добавить термин',
  'glossary.import': 'Импорт',
  'glossary.term': 'Термин',
  'glossary.definition': 'Определение',
  'glossary.example': 'Пример',

  // ===== Employees =====
  'emp.tab.personnel': 'Персонал',
  'emp.tab.reports': 'Отчёты',
  'emp.tab.birthdays': 'Дни Рождения',
  'emp.tab.onboarding': 'Онбординг',
  'emp.tab.documents': 'Документы',
  'emp.tab.employees': 'Сотрудники',
  'emp.tab.candidates': 'Кандидаты',
  'emp.total': 'ВСЕГО',
  'emp.add': 'Сотрудник',
  'emp.docs.sent': 'Отправленные',
  'emp.docs.received': 'Полученные',
  'emp.docs.closing': 'Закрывающие',

  // ===== Statistics =====
  'stats.title': 'Дашборд ОС',
  'stats.all': 'Все',
  'stats.growing': 'Растущие',
  'stats.declining': 'Падающие',
  'stats.achieved': 'Достиг план',
  'stats.not_achieved': 'Не достиг',
  'stats.main_indicators': 'ГЛАВНЫЕ ПОКАЗАТЕЛИ (ГСД)',
  'stats.dept_stats': 'Общие статистики департамента',
  'stats.export_csv': 'CSV экспортирован',
  'stats.import_count': 'Импортировано значений',
  'stats.no_data': 'Нет данных для экспорта',

  // ===== OrgChart =====
  'org.title': 'Организационная структура компании',
  'org.subtitle_prefix': 'Оргсхема',
  'org.departments': 'департаментов',
  'org.divisions': 'отделов',
  'org.settings': 'Настройки',
  'org.add_dept': 'Департамент',
  'org.founder': 'Основатель',
  'org.founder_subtitle': 'Стратегическое руководство',
  'org.ceo': 'Генеральный директор',
  'org.ceo_subtitle': 'Операционное управление',
  'org.company_goal': 'Цель Компании',
  'org.company_vfp': 'ЦКП Компании',
  'org.no_divisions': 'Нет подразделений',
  'org.add_division': 'Добавить отдел',
  'org.loading': 'Загрузка оргсхемы...',

  // ===== Settings =====
  'settings.title': 'Настройки',
  'settings.subtitle': 'Конфигурация системы и управление данными',
  'settings.users': 'Пользователи и роли',
  'settings.export': 'Экспорт данных',
  'settings.database': 'База данных',
  'settings.notifications': 'Уведомления',
  'settings.terminology': 'Терминология',
  'settings.terminology_desc': 'Настройка всех терминов и подписей платформы',

  // ===== Common =====
  'common.save': 'Сохранить',
  'common.cancel': 'Отмена',
  'common.delete': 'Удалить',
  'common.edit': 'Редактировать',
  'common.create': 'Создать',
  'common.loading': 'Загрузка...',
  'common.search': 'Поиск...',
};

// Group labels by module for the settings editor
export const LABEL_GROUPS: { key: string; title: string; prefix: string }[] = [
  { key: 'nav', title: '🧭 Навигация', prefix: 'nav.' },
  { key: 'header', title: '📌 Шапка', prefix: 'header.' },
  { key: 'mobile', title: '📱 Мобильное меню', prefix: 'mobile.' },
  { key: 'academy', title: '🎓 Академия', prefix: 'academy.' },
  { key: 'step', title: '📋 Типы шагов', prefix: 'step.' },
  { key: 'barriers', title: '⚠️ Барьеры обучения', prefix: 'barriers.' },
  { key: 'wc', title: '🔤 Прояснение слов', prefix: 'wc.' },
  { key: 'glossary', title: '📖 Глоссарий', prefix: 'glossary.' },
  { key: 'emp', title: '👥 Сотрудники', prefix: 'emp.' },
  { key: 'stats', title: '📊 Статистика', prefix: 'stats.' },
  { key: 'org', title: '🏢 Оргсхема', prefix: 'org.' },
  { key: 'settings', title: '⚙️ Настройки', prefix: 'settings.' },
  { key: 'common', title: '🔧 Общее', prefix: 'common.' },
];
